spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catboard?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: adminp&ss
